apiVersion: v1
kind: Pod
metadata:
  name: bhuvana-2container-pod
spec:
  containers:
  -  name: nginx-c1
     image: nginx
     ports:
     -  containerPort: 8080
  -  name: watcher-c1
     image: afakharany/watcher
     ports:
     -  containerPort: 8090
